neo4j:
  image: qnib/neo4j
  hostname: neo4j
  ports:
  - 7474:7474
  environment:
  - DC_NAME=dc2
  - FORWARD_TO_LOGSTASH=false
  - CNT_TYPE=service
  volumes:
  - "/var/lib/neo4j/"
  dns: 127.0.0.1
  privileged: true

inventory:
  image: qnib/inventory
  environment:
  - DC_NAME=dc2
  - CNT_TYPE=service
  dns: 127.0.0.1
  hostname: inventory
  privileged: true

consul:
  image: qnib/consul
  ports:
   - "8500:8500"
  environment:
  - DC_NAME=dc2
  - CNT_TYPE=service
  dns: 127.0.0.1
  hostname: consul
  privileged: true

fd20:
  image: qnib/fd20-inv-client
  environment:
  - DC_NAME=dc2
  - CNT_TYPE=service
  dns: 127.0.0.1
  privileged: true

u14:
  image: qnib/u14-terminal
  environment:
  - DC_NAME=dc2
  - CNT_TYPE=service
  dns: 127.0.0.1
  privileged: true
  
