= QNIBInventory
Christian Kniep <christian@qnib.org>
v0.1, 2015-05-04
:neo4j-version: local
:author: Christian Kniep
:twitter: @CQnib

A graphDB model that gathers information using `osquery` and pushes this information into Neo4j.

== Goal

- Show which package a file belongs to, which is executed currently
- build up history of installed packages

== Include a query console

+//console+

becomes:

//console

NOTE: Put the console before any queries!

== Define a http://docs.neo4j.org/chunked/snapshot/cypher-query-lang.html[Cypher] query

 [source,cypher]
 ----
 CREATE (n{name:'cypher'})-[r:LIKES]->({name:'icecream'}) return n.name, r
 ----

becomes:

[source,cypher]
----
CREATE (n{name:'cypher'})-[r:LIKES]->({name:'icecream'}) return n.name, r
----

_Queries are executed in the order they appear on the page during rendering, so make sure they can be performed in that order._
Each query has a green or red button to indicate if the query was successful or not.
The console is set up after the executions, with an empty database, for the reader to play around with the queries.
